# Generated by Django 3.0.3 on 2020-05-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fromsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='item_url',
        ),
        migrations.AddField(
            model_name='search',
            name='amazon_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='ldlc_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='maxgaming_url',
            field=models.TextField(null=True),
        ),
    ]
