# Generated by Django 3.0.3 on 2020-05-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fromsapp', '0003_auto_20200529_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='amazon_url',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='search',
            name='ldlc_url',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='search',
            name='maxgaming_url',
            field=models.TextField(default=''),
        ),
    ]
