# Generated by Django 3.0.3 on 2020-05-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fromsapp', '0004_auto_20200529_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='amazon_price',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='search',
            name='ldlc_price',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='search',
            name='maxgaming_price',
            field=models.CharField(default='', max_length=100),
        ),
    ]
